export const FONTAWESOME_ICONS = [
  { id: 1, class: "RiAccountCircleLine", name: "Tài khoản tròn" },
  { id: 2, class: "RiAccountPinCircleLine", name: "Tài khoản ghim" },
  { id: 3, class: "RiAddCircleLine", name: "Thêm tròn" },
  { id: 4, class: "RiAddLine", name: "Thêm mới" },
  { id: 5, class: "RiAlarmLine", name: "Báo thức" },
  { id: 6, class: "RiAlertLine", name: "Cảnh báo" },
  { id: 7, class: "RiAppsLine", name: "Ứng dụng" },
  { id: 8, class: "RiArchiveLine", name: "Lưu trữ" },
  { id: 9, class: "RiArrowDownLine", name: "Mũi tên xuống" },
  { id: 10, class: "RiArrowLeftLine", name: "Mũi tên trái" },

  { id: 11, class: "RiArrowRightLine", name: "Mũi tên phải" },
  { id: 12, class: "RiArrowUpLine", name: "Mũi tên lên" },
  { id: 13, class: "RiAttachmentLine", name: "Đính kèm" },
  { id: 14, class: "RiAwardLine", name: "Giải thưởng" },
  { id: 15, class: "RiBarChartLine", name: "Biểu đồ cột" },
  { id: 16, class: "RiBatteryLine", name: "Pin" },
  { id: 17, class: "RiBellLine", name: "Chuông" },
  { id: 18, class: "RiBookmarkLine", name: "Đánh dấu trang" },
  { id: 19, class: "RiBriefcaseLine", name: "Cặp hồ sơ" },
  { id: 20, class: "RiBuildingLine", name: "Tòa nhà" },

  { id: 21, class: "RiBusLine", name: "Xe buýt" },
  { id: 22, class: "RiCalculatorLine", name: "Máy tính" },
  { id: 23, class: "RiCalendarLine", name: "Lịch" },
  { id: 24, class: "RiCameraLine", name: "Máy ảnh" },
  { id: 25, class: "RiCarLine", name: "Xe ô tô" },
  { id: 26, class: "RiChat1Line", name: "Trò chuyện" },
  { id: 27, class: "RiCheckLine", name: "Dấu tích" },
  { id: 28, class: "RiCheckboxCircleLine", name: "Ô chọn tròn" },
  { id: 29, class: "RiClipboardLine", name: "Bảng ghi chú" },
  { id: 30, class: "RiCloseLine", name: "Đóng" },

  { id: 31, class: "RiCloudLine", name: "Đám mây" },
  { id: 32, class: "RiCodeLine", name: "Mã lập trình" },
  { id: 33, class: "RiCompassLine", name: "La bàn" },
  { id: 34, class: "RiContactsLine", name: "Danh bạ" },
  { id: 35, class: "RiCouponLine", name: "Phiếu giảm giá" },
  { id: 36, class: "RiDashboardLine", name: "Bảng điều khiển" },
  { id: 37, class: "RiDatabaseLine", name: "Cơ sở dữ liệu" },
  { id: 38, class: "RiDeleteBinLine", name: "Xóa" },
  { id: 40, class: "RiDeviceLine", name: "Thiết bị" },

  { id: 41, class: "RiDownloadLine", name: "Tải xuống" },
  { id: 42, class: "RiEditLine", name: "Chỉnh sửa" },
  { id: 43, class: "RiEmotionLine", name: "Biểu cảm" },
  { id: 44, class: "RiErrorWarningLine", name: "Lỗi cảnh báo" },
  { id: 45, class: "RiEyeLine", name: "Mắt" },
  { id: 46, class: "RiEyeOffLine", name: "Ẩn mắt" },
  { id: 47, class: "RiFileLine", name: "Tệp tin" },
  { id: 48, class: "RiFileCopyLine", name: "Sao chép" },
  { id: 49, class: "RiFileDownloadLine", name: "Tải tệp xuống" },
  { id: 50, class: "RiFileUploadLine", name: "Tải tệp lên" },

  { id: 51, class: "RiFilterLine", name: "Bộ lọc" },
  { id: 52, class: "RiFlagLine", name: "Cờ hiệu" },
  { id: 53, class: "RiFolderLine", name: "Thư mục" },
  { id: 54, class: "RiFolderOpenLine", name: "Mở thư mục" },
  { id: 55, class: "RiFullscreenLine", name: "Toàn màn hình" },
  { id: 56, class: "RiGamepadLine", name: "Tay cầm game" },
  { id: 57, class: "RiGiftLine", name: "Quà tặng" },
  { id: 58, class: "RiGlobalLine", name: "Toàn cầu" },
  { id: 59, class: "RiGpsLine", name: "Định vị GPS" },
  { id: 60, class: "RiGroupLine", name: "Nhóm" },

  { id: 62, class: "RiHardDriveLine", name: "Ổ cứng" },
  { id: 63, class: "RiHeadphoneLine", name: "Tai nghe" },
  { id: 64, class: "RiHeartLine", name: "Trái tim" },
  { id: 65, class: "RiHomeLine", name: "Trang chủ" },
  { id: 66, class: "RiImageLine", name: "Hình ảnh" },
  { id: 67, class: "RiInboxLine", name: "Hộp thư đến" },
  { id: 68, class: "RiInformationLine", name: "Thông tin" },
  { id: 69, class: "RiKeyLine", name: "Chìa khóa" },
  { id: 70, class: "RiLightbulbLine", name: "Ý tưởng" },

  { id: 73, class: "RiLoaderLine", name: "Đang tải" },
  { id: 74, class: "RiLockLine", name: "Khóa" },
  { id: 75, class: "RiLoginBoxLine", name: "Đăng nhập" },
  { id: 76, class: "RiLogoutBoxLine", name: "Đăng xuất" },
  { id: 77, class: "RiMailLine", name: "Thư điện tử" },
  { id: 78, class: "RiMapLine", name: "Bản đồ" },
  { id: 79, class: "RiMapPinLine", name: "Vị trí" },
  { id: 80, class: "RiMenuLine", name: "Menu" },

  { id: 81, class: "RiMessageLine", name: "Tin nhắn" },
  { id: 82, class: "RiMicLine", name: "Micro" },
  { id: 83, class: "RiMoneyDollarCircleLine", name: "Tiền tệ" },
  { id: 84, class: "RiMoonLine", name: "Mặt trăng" },
  { id: 85, class: "RiMoreLine", name: "Xem thêm" },
  { id: 86, class: "RiNavigationLine", name: "Điều hướng" },
  { id: 87, class: "RiNotificationLine", name: "Thông báo" },
  { id: 88, class: "RiPaletteLine", name: "Bảng màu" },
  { id: 89, class: "RiPauseLine", name: "Tạm dừng" },
  { id: 90, class: "RiPenNibLine", name: "Bút mực" },

  { id: 91, class: "RiPhoneLine", name: "Điện thoại" },
  { id: 92, class: "RiPlayLine", name: "Phát" },
  { id: 93, class: "RiPrinterLine", name: "Máy in" },
  { id: 94, class: "RiRefreshLine", name: "Làm mới" },
  { id: 95, class: "RiRepeatLine", name: "Lặp lại" },
  { id: 96, class: "RiRoadMapLine", name: "Lộ trình" },
  { id: 97, class: "RiRocketLine", name: "Tên lửa" },
  { id: 98, class: "RiSaveLine", name: "Lưu" },
  { id: 99, class: "RiSearchLine", name: "Tìm kiếm" },
  { id: 100, class: "RiSendPlaneLine", name: "Gửi đi" },
  { id: 101, class: "RiShieldLine", name: "Lá chắn" },
  { id: 102, class: "RiShoppingBagLine", name: "Túi mua sắm" },
  { id: 103, class: "RiShoppingCartLine", name: "Giỏ hàng" },
  { id: 104, class: "RiShuffleLine", name: "Xáo trộn" },
  { id: 105, class: "RiSignalWifiLine", name: "Tín hiệu Wifi" },
  { id: 106, class: "RiSmartphoneLine", name: "Điện thoại thông minh" },
  { id: 107, class: "RiSoundModuleLine", name: "Âm thanh" },
  { id: 108, class: "RiSpamLine", name: "Thư rác" },
  { id: 109, class: "RiSpeakerLine", name: "Loa" },
  { id: 110, class: "RiSpeedLine", name: "Tốc độ" },

  { id: 111, class: "RiStackLine", name: "Chồng dữ liệu" },
  { id: 112, class: "RiStarLine", name: "Ngôi sao" },
  { id: 113, class: "RiStopLine", name: "Dừng" },
  { id: 114, class: "RiStoreLine", name: "Cửa hàng" },
  { id: 115, class: "RiSuitcaseLine", name: "Vali" },
  { id: 116, class: "RiSunLine", name: "Mặt trời" },
  { id: 117, class: "RiTableLine", name: "Bảng dữ liệu" },
  { id: 118, class: "RiTabletLine", name: "Máy tính bảng" },

  { id: 120, class: "RiTaskLine", name: "Nhiệm vụ" },

  { id: 121, class: "RiTerminalLine", name: "Dòng lệnh" },
  { id: 122, class: "RiThumbUpLine", name: "Thích" },
  { id: 123, class: "RiThumbDownLine", name: "Không thích" },
  { id: 124, class: "RiTimeLine", name: "Thời gian" },
  { id: 125, class: "RiTimerLine", name: "Đồng hồ đếm ngược" },
  { id: 126, class: "RiToolsLine", name: "Công cụ" },

  { id: 128, class: "RiTruckLine", name: "Xe tải" },
  { id: 129, class: "RiTrophyLine", name: "Cúp" },
  { id: 130, class: "RiTvLine", name: "Tivi" },

  { id: 131, class: "RiUploadCloudLine", name: "Tải lên đám mây" },
  { id: 132, class: "RiUsbLine", name: "USB" },
  { id: 133, class: "RiUserAddLine", name: "Thêm người dùng" },
  { id: 134, class: "RiUserFollowLine", name: "Theo dõi" },
  { id: 135, class: "RiUserHeartLine", name: "Yêu thích người dùng" },
  { id: 136, class: "RiUserSettingsLine", name: "Cài đặt người dùng" },
  { id: 137, class: "RiUserStarLine", name: "Người dùng nổi bật" },
  { id: 138, class: "RiUserUnfollowLine", name: "Bỏ theo dõi" },
  { id: 139, class: "RiVideoAddLine", name: "Thêm video" },
  { id: 140, class: "RiVideoDownloadLine", name: "Tải video xuống" },

  { id: 141, class: "RiVideoUploadLine", name: "Tải video lên" },
  { id: 142, class: "RiVipLine", name: "VIP" },
  { id: 143, class: "RiVolumeDownLine", name: "Giảm âm lượng" },
  { id: 144, class: "RiVolumeMuteLine", name: "Tắt tiếng" },
  { id: 145, class: "RiVolumeUpLine", name: "Tăng âm lượng" },
  { id: 146, class: "RiWalletLine", name: "Ví tiền" },
  { id: 147, class: "RiWifiLine", name: "Wifi" },
  { id: 148, class: "RiWifiOffLine", name: "Tắt Wifi" },
  { id: 149, class: "RiWindowLine", name: "Cửa sổ" },
  { id: 150, class: "RiZoomInLine", name: "Phóng to" },

  { id: 151, class: "RiZoomOutLine", name: "Thu nhỏ" },
  { id: 152, class: "RiBookLine", name: "Sách" },
  { id: 153, class: "RiBookOpenLine", name: "Mở sách" },

  { id: 155, class: "RiContactsBookLine", name: "Sổ liên lạc" },
  { id: 156, class: "RiFileListLine", name: "Danh sách tệp" },
  { id: 157, class: "RiFilePaperLine", name: "Giấy tờ" },
  { id: 158, class: "RiFileWarningLine", name: "Tệp cảnh báo" },
  { id: 159, class: "RiFileShieldLine", name: "Tệp bảo mật" },
  { id: 160, class: "RiFileSettingsLine", name: "Cài đặt tệp" },

  { id: 161, class: "RiFolderAddLine", name: "Thêm thư mục" },
  { id: 162, class: "RiFolderDownloadLine", name: "Tải thư mục xuống" },
  { id: 163, class: "RiFolderUploadLine", name: "Tải thư mục lên" },
  { id: 164, class: "RiFolderSharedLine", name: "Thư mục chia sẻ" },
  { id: 165, class: "RiFolderReceivedLine", name: "Thư mục nhận" },
  { id: 166, class: "RiFolderReduceLine", name: "Thu gọn thư mục" },
  { id: 167, class: "RiFolderTransferLine", name: "Chuyển thư mục" },
  { id: 168, class: "RiFolderWarningLine", name: "Thư mục cảnh báo" },
  { id: 169, class: "RiFolderShieldLine", name: "Thư mục bảo mật" },
  { id: 170, class: "RiFolderSettingsLine", name: "Cài đặt thư mục" },

  { id: 171, class: "RiCloudOffLine", name: "Tắt đám mây" },
  { id: 172, class: "RiCloudWindyLine", name: "Mây có gió" },
  { id: 173, class: "RiCloudyLine", name: "Nhiều mây" },
  { id: 174, class: "RiThunderstormsLine", name: "Bão sấm sét" },
  { id: 175, class: "RiSnowyLine", name: "Tuyết rơi" },
  { id: 176, class: "RiMistLine", name: "Sương mù" },
  { id: 177, class: "RiTempColdLine", name: "Nhiệt độ lạnh" },
  { id: 178, class: "RiTempHotLine", name: "Nhiệt độ nóng" },
  { id: 179, class: "RiCelsiusLine", name: "Độ C" },
  { id: 180, class: "RiFahrenheitLine", name: "Độ F" },

  { id: 181, class: "RiHospitalLine", name: "Bệnh viện" },
  { id: 182, class: "RiMedicineBottleLine", name: "Thuốc" },
  { id: 183, class: "RiFirstAidKitLine", name: "Sơ cứu" },
  { id: 184, class: "RiMentalHealthLine", name: "Sức khỏe tâm thần" },
  { id: 185, class: "RiStethoscopeLine", name: "Ống nghe" },
  { id: 186, class: "RiSurgicalMaskLine", name: "Khẩu trang" },
  { id: 187, class: "RiPulseLine", name: "Nhịp tim" },
  { id: 188, class: "RiHeartPulseLine", name: "Tim đập" },
  { id: 189, class: "RiTestTubeLine", name: "Ống nghiệm" },
  { id: 190, class: "RiVirusLine", name: "Virus" },

  { id: 191, class: "RiGovernmentLine", name: "Chính phủ" },
  { id: 192, class: "RiBuilding2Line", name: "Tòa nhà 2" },
  { id: 193, class: "RiBankLine", name: "Ngân hàng" },
  { id: 194, class: "RiAuctionLine", name: "Đấu giá" },
  { id: 196, class: "RiScalesLine", name: "Cân công lý" },
  { id: 198, class: "RiClipboardLine", name: "Bảng kẹp hồ sơ" },
  { id: 199, class: "RiDraftLine", name: "Bản nháp" },
  { id: 200, class: "RiArticleLine", name: "Bài viết" },

  // Giấy tờ / Hồ sơ pháp lý
  { id: 201, class: "RiFileTextLine", name: "Văn bản" },
  { id: 202, class: "RiFileSearchLine", name: "Tra cứu hồ sơ" },
  { id: 203, class: "RiFileEditLine", name: "Soạn thảo" },
  { id: 204, class: "RiFileInfoLine", name: "Thông tin hồ sơ" },
  { id: 205, class: "RiFileLockLine", name: "Hồ sơ mật" },
  { id: 206, class: "RiFileUserLine", name: "Hồ sơ cá nhân" },
  { id: 207, class: "RiFileForbidLine", name: "Hồ sơ bị từ chối" },
  { id: 208, class: "RiFileChartLine", name: "Biểu đồ hồ sơ" },
  { id: 209, class: "RiFileMarkedLine", name: "Hồ sơ đánh dấu" },
  { id: 210, class: "RiFileDamageLine", name: "Hồ sơ lỗi" },

  // Danh tính / Xác thực
  { id: 211, class: "RiPassportLine", name: "Hộ chiếu" },
  { id: 212, class: "RiIdCardLine", name: "CCCD / CMND" },
  { id: 213, class: "RiVerifiedBadgeLine", name: "Đã xác minh" },
  { id: 214, class: "RiMedalLine", name: "Huy chương" },
  { id: 215, class: "RiPoliceBadgeLine", name: "Thẻ công vụ" },

  // Bảo vệ / An ninh
  { id: 216, class: "RiShieldCheckLine", name: "Bảo vệ xác nhận" },
  { id: 217, class: "RiShieldUserLine", name: "Bảo vệ người dùng" },
  { id: 218, class: "RiShieldCrossLine", name: "Bảo vệ y tế" },
  { id: 219, class: "RiShieldStarLine", name: "Bảo vệ nổi bật" },
  { id: 220, class: "RiShieldFlashLine", name: "Bảo vệ khẩn cấp" },

  // Con người / Tổ chức
  { id: 221, class: "RiUserLine", name: "Người dùng" },
  { id: 222, class: "RiUserSearchLine", name: "Tìm kiếm người" },
  { id: 223, class: "RiUserSharedLine", name: "Chuyển người dùng" },
  { id: 224, class: "RiUserReceivedLine", name: "Tiếp nhận người" },
  { id: 225, class: "RiUserVoiceLine", name: "Phát ngôn viên" },
  { id: 226, class: "RiGroupLine", name: "Nhóm người" },
  { id: 227, class: "RiTeamLine", name: "Đội nhóm" },
  { id: 228, class: "RiCommunityLine", name: "Cộng đồng" },
  { id: 229, class: "RiOrganizationChart", name: "Sơ đồ tổ chức" },
  { id: 230, class: "RiAccountBoxLine", name: "Hồ sơ tài khoản" },
];
